import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Search, Printer, Eye } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { fetchBillItems, fetchBills, formatDateTime, formatINR, type Bill } from "@/lib/db";
import { PrintBill, printBill } from "@/components/PrintBill";

export const Route = createFileRoute("/bills")({
  head: () => ({ meta: [{ title: "Bill History — Hotel Inimai" }] }),
  component: BillsPage,
});

function BillsPage() {
  const { data: bills = [] } = useQuery({ queryKey: ["bills"], queryFn: fetchBills });
  const [search, setSearch] = useState("");
  const [date, setDate] = useState("");
  const [active, setActive] = useState<Bill | null>(null);

  const filtered = useMemo(() => bills.filter((b) => {
    if (search && !b.bill_number.toLowerCase().includes(search.toLowerCase())) return false;
    if (date && !b.created_at.startsWith(date)) return false;
    return true;
  }), [bills, search, date]);

  const { data: activeItems = [] } = useQuery({
    queryKey: ["bill_items", active?.id],
    queryFn: () => fetchBillItems(active!.id),
    enabled: !!active,
  });

  return (
    <div className="p-4 lg:p-8 space-y-6 max-w-[1400px] mx-auto">
      <header>
        <h1 className="text-2xl lg:text-3xl font-bold tracking-tight">Bill History</h1>
        <p className="text-muted-foreground">All bills generated by your POS.</p>
      </header>

      <div className="flex flex-col sm:flex-row gap-3">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input placeholder="Search BILL-0001…" className="pl-9 bg-card" value={search} onChange={(e) => setSearch(e.target.value)} />
        </div>
        <Input type="date" value={date} onChange={(e) => setDate(e.target.value)} className="sm:w-48 bg-card" />
      </div>

      <div className="bg-card rounded-2xl border overflow-hidden shadow-[var(--shadow-soft)]">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-muted/50 text-muted-foreground">
              <tr>
                <th className="text-left px-5 py-3">Bill #</th>
                <th className="text-left px-5 py-3">Date & Time</th>
                <th className="text-right px-5 py-3">Amount</th>
                <th className="text-right px-5 py-3">Actions</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((b) => (
                <tr key={b.id} className="border-t hover:bg-muted/30">
                  <td className="px-5 py-3 font-semibold">{b.bill_number}</td>
                  <td className="px-5 py-3 text-muted-foreground">{formatDateTime(b.created_at)}</td>
                  <td className="px-5 py-3 text-right font-bold">{formatINR(Number(b.total_amount))}</td>
                  <td className="px-5 py-3 text-right">
                    <Button size="sm" variant="outline" onClick={() => setActive(b)}><Eye className="h-3.5 w-3.5 mr-1" />View</Button>
                  </td>
                </tr>
              ))}
              {filtered.length === 0 && (
                <tr><td colSpan={4} className="px-5 py-12 text-center text-muted-foreground">No bills found.</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      <Dialog open={!!active} onOpenChange={(o) => !o && setActive(null)}>
        <DialogContent className="max-w-md">
          <DialogHeader><DialogTitle>{active?.bill_number}</DialogTitle></DialogHeader>
          {active && (
            <div className="space-y-3">
              <div className="text-sm text-muted-foreground">{formatDateTime(active.created_at)}</div>
              <div className="border rounded-lg divide-y">
                {activeItems.map((it) => (
                  <div key={it.id} className="p-3 flex justify-between text-sm">
                    <div>
                      <div className="font-medium">{it.item_name}</div>
                      <div className="text-xs text-muted-foreground">{formatINR(Number(it.price))} × {it.quantity}</div>
                    </div>
                    <div className="font-semibold">{formatINR(Number(it.subtotal))}</div>
                  </div>
                ))}
              </div>
              <div className="flex justify-between font-bold text-lg pt-2">
                <span>Total</span><span className="text-primary">{formatINR(Number(active.total_amount))}</span>
              </div>
              <Button className="w-full gap-2" onClick={() => printBill()}>
                <Printer className="h-4 w-4" /> Reprint Bill
              </Button>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {active && (
        <PrintBill
          billNumber={active.bill_number}
          createdAt={active.created_at}
          lines={activeItems.map((i) => ({ item_name: i.item_name, quantity: i.quantity, price: Number(i.price) }))}
          total={Number(active.total_amount)}
        />
      )}
    </div>
  );
}